debug: true
maximum-item-damage: 3

# Use EquipmentSlot values (https://hub.spigotmc.org/javadocs/spigot/org/bukkit/inventory/EquipmentSlot.html)
applied-slots-drop-broken:
    - HEAD
    - CHEST
    - LEGS
    - FEET
    - HAND
    - OFF_HAND

repair-command:
    base-cost:
        wood: 200
        stone: 400
        leather: 600
        gold: 700
        chain: 900
        iron: 1200
        bow: 1600
        diamond: 1600
        netherite: 2000
    enchant-multiplier-per-level:
        max-level-1: 3.0
        max-level-2: 2.0
        max-level-3: 1.6
        max-level-4: 1.2
        max-level-5: 1.0
        cursed: -0.5
    max-cost: 100000
